# Generated by Django 3.2 on 2023-04-20 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentsregister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=200)),
                ('sclass', models.IntegerField(blank=True)),
                ('ssession', models.CharField(max_length=10)),
                ('sdate', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(blank=True, default=1)),
            ],
        ),
    ]
